### ISSUE TITLE
Crash on Quilt 0.23.1

### ISSUE THREAD

**Issue by mrElken** [anviaan/MoreBeeInfo#5]
Minecraft 1.20.2
Quilt 0.23.1
Mods:
- Quilted Fabric API 8.0.0-alpha.3+0.91.2-1.20.2
- MoreBeeInfo 1.1.2

Crash report:
[crash-2024-02-03_12.50.35.1219-quilt_loader.txt](https://github.com/anviaan/MoreBeeInfo/files/14150923/crash-2024-02-03_12.50.35.1219-quilt_loader.txt)

**Comment by anviaan** [comment]
Actually works on version 1.3
